### ISSUE TITLE
Forked maintained apollo-client-maven-plugin

### ISSUE THREAD

**Issue by Sparow199** [Cox-Automotive/apollo-client-maven-plugin#13]
I merged the pending PRs in the main project and I update the plugin to last version of the Apollo GraphQL compiler. In my company project, the plugin work only with flat queries (no fragments).
I'm working on the project to align it with the Gradle version. 

Feel free to contribute by submitting your PRs to develop a branch of my fork.
Thanks :).

[Apollo-client-maven-plugin](https://github.com/Sparow199/apollo-client-maven-plugin)

**Comment by apottere** [comment]
Sorry, this project completely fell through the cracks.  Thanks for picking this up!  I'll update the readme, etc to point to your fork.
