### ISSUE TITLE
Windows: character to be escaped is missing

### ISSUE THREAD

**Issue by gdrouet** [Cox-Automotive/apollo-client-maven-plugin#2]
Plugin fails on windows. The MOJO certainly copies generated files with the default platform charset instead of UTF-8.

**Comment by metalpalo** [comment]
Exactly same problem on windows when generating queries.

For successfull run on win I needed to make two small changes in mojo class(search chunks):

replace(**Regex(**"/"**)**, File.separator)  -> replace("/", File.separator)

File(it, "node") -> File(it, "**node.exe**")

**Comment by metalpalo** [comment]
I've overtaken your fix to my clone and it works on Windows now!
When we can expect new release?
Thank You very much

**Comment by samo717** [comment]
Hello,
I am facing the same problem as mentioned in the title of this issue. When is new release (which will include the change above) going to be created?
Thanks
